name: Deploy frontend application and scan with DeepSource

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_DOCKER_HUB_USERNAMELAB6 }}
          password: ${{ secrets.DOCKER_HUB_TOKENLAB06 }}

      - name: Prepare the docker-compose run
        run: ls -l

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: kengchayodom/234-deploylab11-06:latest

      - name: Copy docker-compose file via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST_SERVERLAB06 }}
          username: ${{ secrets.HOST_USER_NAMELAB06 }}
          key: ${{ secrets.HOST_SSH_LAB06 }}
          port: 22
          source: "docker-compose.yml"
          target: "/home/ubuntu/frontend"

      - name: Deploy using Docker Compose
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST_SERVERLAB06 }}
          username: ${{ secrets.HOST_USER_NAMELAB06 }}
          key: ${{ secrets.HOST_SSH_LAB06 }}
          port: 22
          script: |
            cd /home/ubuntu/frontend
            echo ${{ secrets.DOCKER_HUB_TOKENLAB06 }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAMELAB6 }} --password-stdin
            docker compose down
            docker compose pull
            docker compose up -d
            rm -rf /home/ubuntu/frontend

